(defun variable-p (x)
  (and (symbolp x)
       (equal (char (symbol-name x) 0) #\?)))

(defun length-form (form &optional (n 0))
  (if (not (null form))
      (if (atom (car form))
          (if (member (car form) '(implies and or equiv))
              (length-form (cdr form) (+ n 1))
              (length-form (cdr form) n))
          (progn (setf n (+ n (length-form (car form))))
                 (length-form (cdr form) n)))
      n))
